GET https://dsdeisi.pythonanywhere.com/inqueritos-courses/23-24
Accept: application/json

###
GET https://dsdeisi.pythonanywhere.com/inqueritos-teachers/23-24
Accept: application/json

###
GET https://dsdeisi.pythonanywhere.com/inqueritos-teacher-courses/23-24/1
Accept: application/json

###
GET http://localhost:8010/api/export?token=9810692789&startId=50093&endId=59943
Accept: application/json